#!/bin/bash
# Ubuntu 16.04
# execute as root
apt-get update -y
apt-get upgrade -y
apt-get install bash-completion git python python-pip sudo vim -y
pip install --upgrade pip
pip install --upgrade virtualenv
