#!/bin/bash
# Location to place backups.
# su - postgres
# crontab -e
# 0 3 * * * SCRIPT_PATH

backup_dir="/home/developer/backups"
log="/home/developer/backups/log"
number_of_days=30
#databases=`psql -l -t | cut -d'|' -f1 | sed -e 's/ //g' -e '/^$/d' | sed '/:/d'` # TODAS LAS BD
databases="
  sgi
  sgi_template
"

backup_date=`date +%Y-%m-%d`

for i in $databases; do
  file=${i}_${backup_date}.tar
  pg_dump -Ft $i > $backup_dir/$file 

  if [ `echo $?` == 0 ];then
      echo "DONE - $file" >> log
  else
      echo "FAIL - $file" >> log
  fi
done
find $backup_dir -type f -prune -mtime +$number_of_days -exec rm -f {} \;
