#!/bin/bash

bk_dir="/backups/local/"
date=`date +%Y_%m_%d`
exp_days=30
dbs=`psql -l -t | cut -d'|' -f1 | sed -e 's/ //g' -e '/^$/d'`
to_backup=`cat /backups/to_backup_local`
log='/var/log/odoo/backups_local.log'

for db in $dbs; do
  if [[ ${to_backup[*]} =~ $db ]] ; then 
    pg_dump -Ft $db > $bk_dir$db\_$date.tar
    if [ `echo $?` == 0 ];then
        echo "DONE - $db at $date" >> log
    else
        echo "FAIL - $db at $date" >> log
    fi
  fi
done

find $bk_dir -type f -prune -mtime +$exp_days -exec rm -f {} \;
