#!/bin/bash

bk_dir="/backups/remote/"
date=`date +%Y_%m_%d`
exp_days=30
to_backup=`cat /backups/to_backup_remote`
log='/var/log/odoo/backups_remote.log'

for db in $to_backup; do
    server=`echo $db | cut -d '@' -f2 | cut -d ':' -f1`
    f=`echo $db | cut -d '@' -f2 | cut -d ':' -f2 | rev | cut -d '/' -f1 |rev`
    mkdir -p $bk_dir$server/
    scp -q $db\_$date.tar $bk_dir$f\_$date.tar
    if [ `echo $?` == 0 ];then
        echo "DONE - $server:$f at $date" >> log
    else
        echo "FAIL - $server:$f at $date" >> log
    fi
done

find $bk_dir -type f -prune -mtime +$exp_days -exec rm -f {} \;
