#!/bin/bash

inst_dir='/opt/'
admin_user='htk'
log_dir='/var/log/odoo/'
config_dir='/etc/'

usage() { 
    echo "Usage: $0 <NAME>"
    exit 1
}

if [ ! $1 ]; then
    usage
fi

name=$1

# if [ -d $inst_dir$name ]; then
    '/etc/init.d/'$name stop
    sudo -u postgres dropuser $name
    rm '/etc/init.d/'$name
    rm $config_dir$name.conf
    rm $log_dir$name.log
    rm -r $inst_dir$name
    gpasswd -d $admin_user $name
    userdel -r $name
# else
#     echo "Instance not found"
#     exit 1
# fi
